#!/bin/bash
SBATCH --time=00:15:00
SBATCH -N 1
SBATCH --ntasks-per-node=16

. /etc/bashrc
. /etc/profile.d/modules.sh

#source ~/pyenv/bin/activate

#pyenv activate venv

APP=./cpi
ARGS=""
#!/bin/sh

python skge/run_transe.py --fin data/lubm1_uri.bin \
       --test-all 50 --nb 100 --me 500 \
       --margin 2.0 --lr 0.1 --ncomp 50  --incr 10 --finfo info-assignment.txt --fembed embeddings-lubm1-exp.out  --ftax data/taxonomy
